Add friends likes
Bikkul/java-filmorate pull request #2
Opened 2022-11-18 22:52 UTC by Bikkul

2022-11-19 15:18 UTC, Frilock requested changes
Добрый день, интересный вариант реализации, а почему вы друзей как коллекцию на пользователя не добавите? В целом по коду замечаний нет, кроме разве что удаления комментариев в коде.

2022-11-19 15:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmrate/dao/impl/InMemoryLikeStorage.java
> +        likedFilms.get(filmId)
в одну строчку влезает

2022-11-19 15:18 UTC, Frilock commented on src/main/java/ru/yandex/practicum/filmrate/service/ValidationService.java
> +            //log.warn("Дата рождения не может быть в будущем. Сейчас {}, указанная дата {}", LocalDate.now(),
Предлагаю комментарии удалить, зачем они?

2022-11-19 15:55 UTC, Bikkul commented
Ну насчет коллекции друзей в пользователе, я решил разделить ответственность, чтоб пользователи хранили информацию только о себе, а друзья о себе

2022-11-20 10:57 UTC, Frilock approved these changes
Принял, хорошее решение.

2022-11-20 23:11 UTC, merged